"""Blueprint tools, including the guarded import from a public URL."""
from __future__ import annotations

from homeassistant.core import HomeAssistant

from ..yaml_sources import is_within, load_yaml_ha, parse_yaml_ha
from .common import _async_read_file, _async_write_file, _caller_context, _slugify
from .tools_audit import _tool_get_automation
from .tools_system import _auto_backup


# ── ha_create_blueprint ──────────────────────────────────────────────────────
async def _tool_ha_create_blueprint(hass: HomeAssistant, params: dict) -> dict:
    """Convert an existing automation into a reusable Blueprint YAML file."""
    import re
    import os
    import yaml as _yaml

    # Internal backup — AI should NOT call ha_backup_create before this tool
    await _auto_backup(hass, "_tool_ha_create_blueprint")

    automation_ref = params.get("automation_entity_id", "").strip()
    blueprint_name = params.get("blueprint_name", "").strip()
    blueprint_description = params.get("blueprint_description", "").strip()

    # Robust inputs parsing — AI agents may send various formats
    raw_inputs = params.get("inputs")
    custom_inputs: dict = {}
    if raw_inputs:
        if isinstance(raw_inputs, str):
            try:
                import json as _json
                raw_inputs = _json.loads(raw_inputs)
            except Exception:
                raw_inputs = {}
        if isinstance(raw_inputs, dict):
            for k, v in raw_inputs.items():
                if isinstance(v, dict):
                    # Proper dict input — validate it has required blueprint fields
                    if "name" in v or "selector" in v:
                        custom_inputs[k] = v
                    else:
                        # Dict without name/selector — wrap as input with selector
                        custom_inputs[k] = {"name": k, "selector": v}
                elif isinstance(v, str):
                    # AI may send a JSON string as value — try to parse it
                    try:
                        import json as _json2
                        parsed = _json2.loads(v)
                        if isinstance(parsed, dict):
                            # The AI sent the ENTIRE inputs dict as a single JSON string value
                            # under a dummy key like "json" — unwrap it
                            for pk, pv in parsed.items():
                                if isinstance(pv, dict):
                                    custom_inputs[pk] = pv
                            continue
                    except Exception:
                        pass
                    # Simple string — likely an entity_id default
                    domain = v.split(".")[0] if "." in v else ""
                    inp = {"name": k}
                    if domain:
                        inp["default"] = v
                        inp["selector"] = {"entity": {"domain": domain}}
                    else:
                        inp["default"] = v
                    custom_inputs[k] = inp
        else:
            custom_inputs = {}  # invalid format — will auto-detect

    if not automation_ref:
        return {"error": "automation_entity_id is required"}

    # ── Step 1: fetch the automation YAML ────────────────────────────────────
    auto_data = await _tool_get_automation(hass, {"entity_id": automation_ref})
    if "error" in auto_data:
        return {"error": f"Could not read automation: {auto_data['error']}"}

    raw_yaml: str = auto_data.get("yaml", "")
    if not raw_yaml:
        return {"error": "Automation returned empty YAML. Cannot create blueprint."}

    try:
        auto_dict: dict = _yaml.safe_load(raw_yaml) or {}
    except Exception as exc:
        return {"error": f"Failed to parse automation YAML: {exc}"}

    alias: str = auto_dict.get("alias") or automation_ref
    if not blueprint_name:
        blueprint_name = alias
    if not blueprint_description:
        blueprint_description = (
            f"Blueprint generated by HACA from automation \"{alias}\". "
            "Edit this description to explain the use case."
        )

    # ── Step 2: auto-detect entity_id inputs if not provided by caller ───────
    if not custom_inputs:
        # Collect all entity_id values from triggers + actions + conditions
        entity_ids_found: list[str] = []
        body_str = _yaml.dump(auto_dict, allow_unicode=True, default_flow_style=False)
        # Match entity_id patterns like light.salon, sensor.temperature, etc.
        entity_ids_found = list(dict.fromkeys(
            re.findall(r'\b([a-z_]+\.[a-z0-9_]+)\b', body_str)
        ))
        # Filter: only real HA entity-looking ones (skip common YAML keys)
        _SKIP = {"true", "false", "null", "on", "off", "single", "parallel",
                 "queued", "restart", "trigger.entity_id", "trigger.to",
                 "trigger.from", "state.entity_id"}
        entity_ids_found = [
            e for e in entity_ids_found
            if "." in e and e not in _SKIP and not e.startswith("trigger.")
            and not e.startswith("condition.") and not e.startswith("action.")
        ][:6]  # cap at 6 inputs

        for eid in entity_ids_found:
            domain = eid.split(".")[0]
            slug = eid.replace(".", "_")
            custom_inputs[slug] = {
                "name": eid,
                "default": eid,
                "selector": {"entity": {"domain": domain}},
            }

    # ── Step 3: build the blueprint body ─────────────────────────────────────
    # Extract automation body keys (everything except metadata)
    _META_KEYS = {"id", "alias", "description", "use_blueprint", "mode",
                  "max", "max_exceeded", "trace", "initial_state"}
    body_keys = [
        k for k in ["triggers", "trigger", "conditions", "condition",
                     "actions", "action", "mode", "variables"]
        if k in auto_dict
    ]

    bp_body: dict = {k: auto_dict[k] for k in body_keys if k in auto_dict}

    # Substitute entity_ids with !input references
    if custom_inputs:
        body_str = _yaml.dump(bp_body, allow_unicode=True, default_flow_style=False)
        for slug, inp in custom_inputs.items():
            default_val = inp.get("default", "")
            if default_val:
                body_str = body_str.replace(
                    f"'{default_val}'", f"!input {slug}"
                ).replace(
                    f'"{default_val}"', f"!input {slug}"
                ).replace(default_val, f"!input {slug}")
        # Do NOT round-trip through safe_load — !input is not a standard YAML tag
        # Keep body_str as raw YAML text with !input references

    # Build input section — clean format for HA blueprints
    input_section: dict = {}
    for slug, inp in custom_inputs.items():
        # Ensure each input has at minimum: name + selector
        clean_inp = {}
        if "name" in inp:
            clean_inp["name"] = inp["name"]
        if "description" in inp and inp["description"] != inp.get("default"):
            clean_inp["description"] = inp["description"]
        if "selector" in inp:
            clean_inp["selector"] = inp["selector"]
        if "default" in inp:
            clean_inp["default"] = inp["default"]
        input_section[slug] = clean_inp if clean_inp else inp

    blueprint_header: dict = {
        "blueprint": {
            "name": blueprint_name,
            "description": blueprint_description,
            "domain": "automation",
            "input": input_section,
        }
    }

    # Dump header (no !input tags) and body separately
    header_yaml = _yaml.dump(
        blueprint_header,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
    )

    if custom_inputs:
        # body_str already has !input references as raw text
        bp_yaml = header_yaml + "\n" + body_str
    else:
        bp_body_yaml = _yaml.dump(bp_body, allow_unicode=True, default_flow_style=False)
        bp_yaml = header_yaml + "\n" + bp_body_yaml

    # ── Step 4: write the file ────────────────────────────────────────────────
    slug_name = _slugify(blueprint_name, 60)
    bp_dir = hass.config.path("blueprints", "automation", "haca")
    await hass.async_add_executor_job(os.makedirs, bp_dir, 0o755, True)
    bp_path = os.path.join(bp_dir, f"{slug_name}.yaml")

    try:
        _bp_header = (
            f"# Blueprint generated by HACA from automation \"{alias}\"\n"
            f"# Fichier : {bp_path}\n\n"
        )
        await _async_write_file(hass, bp_path, _bp_header + bp_yaml)
    except Exception as exc:
        return {"error": f"Failed to write blueprint file: {exc}", "path": bp_path}

    # ── Step 5: reload blueprints ─────────────────────────────────────────────
    try:
        await hass.services.async_call("blueprint", "reload", blocking=True, context=_caller_context())
    except Exception:
        pass  # non-fatal — blueprints reload on next HA restart anyway

    return {
        "success": True,
        "path": bp_path,
        "blueprint_name": blueprint_name,
        "inputs_detected": list(custom_inputs.keys()),
        "yaml": bp_yaml,
        "message": (
            f"Blueprint '{blueprint_name}' created in {bp_path}. "
            "Visible in Settings → Blueprints. "
            "To use it: Settings → Automations → Create → From a blueprint."
        ),
    }


# ── BLUEPRINTS ────────────────────────────────────────────────────────────────

def _resolve_blueprint_path(hass: "HomeAssistant", path_ref: str) -> tuple[str | None, dict | None]:
    """Resolve a blueprint path reference and confirm it stays under /config/blueprints/.

    Returns ``(path, None)`` or ``(None, error_dict)``. Both absolute paths and
    ``..`` segments are rejected once resolved: these tools are driven by an
    LLM, and an unchecked path turns them into arbitrary file read / write /
    delete over the whole config directory.
    """
    import os

    bp_base = hass.config.path("blueprints")
    fpath = path_ref if os.path.isabs(path_ref) else os.path.join(bp_base, path_ref)

    if not is_within(fpath, bp_base):
        return None, {"error": "path must stay inside /config/blueprints/"}
    return os.path.normpath(fpath), None


async def _async_resolve_blueprint_path(
    hass: "HomeAssistant", path_ref: str
) -> tuple[str | None, dict | None, bool]:
    """``_resolve_blueprint_path`` plus an existence check, off the event loop.

    The guard calls ``os.path.realpath`` (which follows symlinks) and the
    callers then stat the result: four blocking filesystem calls that Home
    Assistant now logs a warning for. Returns ``(path, error, exists)``.
    """
    import os

    def _work() -> tuple[str | None, dict | None, bool]:
        fpath, err = _resolve_blueprint_path(hass, path_ref)
        if err:
            return None, err, False
        return fpath, None, os.path.isfile(fpath)

    return await hass.async_add_executor_job(_work)


async def _tool_ha_list_blueprints(hass: HomeAssistant, params: dict) -> dict:
    """List all installed blueprints (automation + script domains)."""
    import os
    domain_filter = params.get("domain", "").strip().lower() or None
    bp_base = hass.config.path("blueprints")
    results: list[dict] = []

    def _walk_blueprints() -> list[tuple[str, str, str, str]] | None:
        """(domain, path, rel_path, filename) for every blueprint on disk.

        ``os.walk`` is the one genuinely expensive filesystem call in this
        module; it runs here in the executor, together with the two isdir()
        probes that used to sit on the event loop in front of it.
        """
        if not os.path.isdir(bp_base):
            return None
        found: list[tuple[str, str, str, str]] = []
        for domain in ("automation", "script"):
            if domain_filter and domain_filter != domain:
                continue
            domain_dir = os.path.join(bp_base, domain)
            if not os.path.isdir(domain_dir):
                continue
            for root, _dirs, files in os.walk(domain_dir):
                for fname in sorted(files):
                    if not fname.endswith(".yaml"):
                        continue
                    fpath = os.path.join(root, fname)
                    found.append((domain, fpath, os.path.relpath(fpath, bp_base), fname))
        return found

    walked = await hass.async_add_executor_job(_walk_blueprints)
    if walked is None:
        return {"blueprints": [], "message": "No blueprints directory found."}

    for domain, fpath, rel_path, fname in walked:
        try:
            # HA's loader, not safe_load: !input is a standard HA tag
            # and PyYAML has no constructor for it, so every real
            # blueprint used to come back as {"path", "error"}.
            data = await hass.async_add_executor_job(load_yaml_ha, str(fpath))
            bp_meta = data.get("blueprint", {}) if isinstance(data, dict) else {}
            results.append({
                "domain": domain,
                "path": rel_path,
                "name": bp_meta.get("name", fname),
                "description": bp_meta.get("description", ""),
                "source_url": bp_meta.get("source_url", ""),
                "inputs": list(bp_meta.get("input", {}).keys()),
            })
        except Exception as exc:
            results.append({"domain": domain, "path": rel_path, "error": str(exc)})

    return {
        "blueprints": results,
        "total": len(results),
    }


async def _tool_ha_get_blueprint(hass: HomeAssistant, params: dict) -> dict:
    """Read the full YAML of an installed blueprint."""
    path_ref = params.get("path", "").strip()
    if not path_ref:
        return {"error": "path required (relative to /config/blueprints/, e.g. 'automation/haca/my_bp.yaml')"}

    fpath, err, exists = await _async_resolve_blueprint_path(hass, path_ref)
    if err:
        return err

    if not exists:
        return {"error": f"Blueprint file not found: {fpath}"}

    try:
        content = await _async_read_file(hass, fpath)
        # HA's loader resolves !input; PyYAML's safe_load raises on it.
        data = await hass.async_add_executor_job(load_yaml_ha, fpath)
    except Exception as exc:
        return {"error": f"Failed to read blueprint: {exc}"}

    bp_meta = data.get("blueprint", {}) if isinstance(data, dict) else {}
    # "parsed" is deliberately not returned: the body holds Input objects,
    # which are not JSON-serialisable. `yaml` (raw text) is the source of
    # truth for any edit, and the metadata below is plain and JSON-safe.
    return {
        "path": fpath,
        "name": bp_meta.get("name", ""),
        "description": bp_meta.get("description", ""),
        "domain": bp_meta.get("domain", "automation"),
        "inputs": bp_meta.get("input", {}),
        "yaml": content,
    }


async def _tool_ha_update_blueprint(hass: HomeAssistant, params: dict) -> dict:
    """Replace an existing blueprint file with new YAML, written verbatim."""
    path_ref = params.get("path", "").strip()
    if not path_ref:
        return {"error": "path required (relative to /config/blueprints/)"}

    # Backup automatique avant opération destructive
    await _auto_backup(hass, "_tool_ha_update_blueprint")

    fpath, err, exists = await _async_resolve_blueprint_path(hass, path_ref)
    if err:
        return err

    if not exists:
        return {"error": f"Blueprint file not found: {fpath}. Use ha_create_blueprint to create it."}

    # Field-level patching is gone: it round-tripped the file through
    # yaml.dump(), which cannot represent HA's !input tags — so it only ever
    # "worked" on blueprints that had no inputs, and silently mangled the rest.
    new_yaml = params.get("yaml")
    if not new_yaml:
        return {"error": "pass the full blueprint as yaml= — field-level patching is "
                         "unavailable because HA !input tags do not round-trip "
                         "through a YAML dump. Read the current file with "
                         "ha_get_blueprint(path), edit the text, send it back."}

    try:
        parsed = await hass.async_add_executor_job(parse_yaml_ha, new_yaml)
    except Exception as exc:
        return {"error": f"Provided YAML is invalid: {exc}"}
    if not isinstance(parsed, dict) or "blueprint" not in parsed:
        return {"error": "YAML has no top-level 'blueprint:' key"}

    try:
        await _async_write_file(hass, str(fpath), new_yaml)  # verbatim
    except Exception as exc:
        return {"error": f"Failed to write blueprint: {exc}"}

    try:
        await hass.services.async_call("blueprint", "reload", blocking=True, context=_caller_context())
    except Exception:
        pass

    return {
        "success": True,
        "path": fpath,
        "name": parsed["blueprint"].get("name", "") if isinstance(parsed["blueprint"], dict) else "",
        "message": f"Blueprint updated at {fpath}. Reloaded.",
    }


async def _tool_ha_remove_blueprint(hass: HomeAssistant, params: dict) -> dict:
    """Delete a blueprint file from /config/blueprints/."""
    import os
    path_ref = params.get("path", "").strip()
    if not path_ref:
        return {"error": "path required"}

    # Backup automatique avant opération destructive
    await _auto_backup(hass, "_tool_ha_remove_blueprint")

    # Safety: must really resolve inside /config/blueprints/. A bare
    # startswith() on the joined path let "../../secrets.yaml" through, since
    # the unresolved string still began with the base directory.
    fpath, err, exists = await _async_resolve_blueprint_path(hass, path_ref)
    if err:
        return {"error": "Cannot delete files outside /config/blueprints/"}

    if not exists:
        return {"error": f"Blueprint file not found: {fpath}"}

    try:
        await hass.async_add_executor_job(os.remove, fpath)
    except Exception as exc:
        return {"error": f"Failed to delete blueprint: {exc}"}

    try:
        await hass.services.async_call("blueprint", "reload", blocking=True, context=_caller_context())
    except Exception:
        pass

    return {
        "success": True,
        "deleted": fpath,
        "message": f"Blueprint deleted: {fpath}",
    }


# Blueprints live in one subfolder per domain. The value comes out of the
# downloaded document, so it is attacker-controlled text on its way into a path.
_BLUEPRINT_DOMAINS = {"automation", "script", "template"}


# A blueprint is a small YAML document; anything past this is not one, and the
# body is held in memory before being written.
_BLUEPRINT_MAX_BYTES = 2 * 1024 * 1024


# Hops followed by hand so every one of them is re-checked: a URL on a public
# host that 302s to 169.254.169.254 would otherwise walk straight through the
# check below.
_BLUEPRINT_MAX_REDIRECTS = 3


async def _async_check_public_url(hass: "HomeAssistant", url: str) -> dict | None:
    """Confirm a URL is http(s) on a public host. Returns an error dict or None.

    These tools are driven by an LLM, and the fetch runs from inside the Home
    Assistant host: an unchecked URL turns the importer into a GET primitive
    against everything that host can reach — the supervisor API, a router admin
    page, a cloud metadata endpoint — with the response body written to disk
    where the caller can read it back.

    Every address the name resolves to must be public: a hostname resolving to
    both a public and a private address is refused. This is a resolve-then-fetch
    check, so a name that changes answer between the two (DNS rebinding) is not
    covered; blocking that needs the connection itself pinned to the checked
    address, which aiohttp does not expose here.
    """
    import ipaddress
    import socket
    from urllib.parse import urlparse

    try:
        parsed = urlparse(url)
    except Exception as exc:  # noqa: BLE001 — malformed input, not a crash
        return {"error": f"Invalid URL: {exc}"}

    if parsed.scheme not in ("http", "https"):
        return {"error": "url must be http:// or https:// (raw YAML, "
                         "e.g. https://raw.githubusercontent.com/...)"}
    host = parsed.hostname
    if not host:
        return {"error": "url has no host"}

    port = parsed.port or (443 if parsed.scheme == "https" else 80)
    try:
        infos = await hass.async_add_executor_job(
            socket.getaddrinfo, host, port, 0, socket.SOCK_STREAM
        )
    except Exception as exc:  # noqa: BLE001 — DNS failure is a caller error
        return {"error": f"Cannot resolve '{host}': {exc}"}

    for info in infos:
        addr = info[4][0]
        try:
            ip = ipaddress.ip_address(addr)
        except ValueError:
            return {"error": f"Cannot validate address '{addr}' for '{host}'"}
        if (ip.is_private or ip.is_loopback or ip.is_link_local
                or ip.is_reserved or ip.is_multicast or ip.is_unspecified):
            return {"error": f"Refusing to fetch from '{host}' ({addr}): "
                             f"blueprints are imported from public URLs only, "
                             f"not from addresses inside this network."}
    return None


async def _tool_ha_import_blueprint(hass: HomeAssistant, params: dict) -> dict:
    """Import a community blueprint from a URL (raw YAML) into /config/blueprints/<domain>/imported/."""
    import os
    import aiohttp
    url = params.get("url", "").strip()
    if not url:
        return {"error": "url required (raw YAML URL, e.g. raw.githubusercontent.com/...)"}

    content = None
    try:
        async with aiohttp.ClientSession() as session:
            for _hop in range(_BLUEPRINT_MAX_REDIRECTS + 1):
                err = await _async_check_public_url(hass, url)
                if err is not None:
                    return err
                async with session.get(
                    url,
                    timeout=aiohttp.ClientTimeout(total=30),
                    allow_redirects=False,
                ) as resp:
                    if resp.status in (301, 302, 303, 307, 308):
                        location = resp.headers.get("Location", "")
                        if not location:
                            return {"error": f"HTTP {resp.status} with no Location header"}
                        from urllib.parse import urljoin
                        url = urljoin(str(resp.url), location)
                        continue
                    if resp.status != 200:
                        return {"error": f"HTTP {resp.status} fetching blueprint URL"}
                    raw = await resp.content.read(_BLUEPRINT_MAX_BYTES + 1)
                    if len(raw) > _BLUEPRINT_MAX_BYTES:
                        return {"error": f"Blueprint exceeds "
                                         f"{_BLUEPRINT_MAX_BYTES // 1024} KB — not a blueprint."}
                    try:
                        encoding = resp.get_encoding() or "utf-8"
                    except Exception:  # noqa: BLE001 — no charset, assume UTF-8
                        encoding = "utf-8"
                    content = raw.decode(encoding, errors="replace")
                    break
            else:
                return {"error": f"More than {_BLUEPRINT_MAX_REDIRECTS} redirects — giving up."}
    except Exception as exc:
        return {"error": f"Failed to fetch URL: {exc}"}

    if content is None:
        return {"error": "Failed to fetch URL: empty response"}

    try:
        # HA's parser: most community blueprints use !input, which safe_load
        # cannot construct — the import used to fail on them outright.
        data = await hass.async_add_executor_job(parse_yaml_ha, content)
    except Exception as exc:
        return {"error": f"Downloaded content is not valid YAML: {exc}"}

    if not isinstance(data, dict) or "blueprint" not in data:
        return {"error": "Downloaded YAML has no 'blueprint:' key — not a valid HA blueprint"}

    bp_block = data["blueprint"] if isinstance(data["blueprint"], dict) else {}

    # Build filename from blueprint name. Everything in bp_block comes from the
    # downloaded document, so nothing here may assume a type.
    bp_name = bp_block.get("name") or "imported_blueprint"
    if not isinstance(bp_name, str):
        bp_name = str(bp_name)
    slug = _slugify(bp_name, 60)

    # `domain` is a value read out of the *downloaded* document and it used to
    # go straight into the output path: `domain: ../../` — or an absolute path,
    # which os.path.join() lets win outright — wrote the fetched body anywhere
    # the HA process can write. The other three blueprint tools were hardened
    # in 1.7.7; this one never went through _resolve_blueprint_path at all.
    domain = bp_block.get("domain", "automation")
    if not isinstance(domain, str) or domain not in _BLUEPRINT_DOMAINS:
        return {"error": f"Blueprint declares an unsupported domain "
                         f"{domain!r} — expected one of {sorted(_BLUEPRINT_DOMAINS)}."}
    if not slug:
        return {"error": f"Blueprint name {bp_name!r} yields an empty filename."}

    bp_inputs = bp_block.get("input", {})

    bp_base = hass.config.path("blueprints")
    out_dir = os.path.join(bp_base, domain, "imported")
    out_path = os.path.join(out_dir, f"{slug}.yaml")
    if not await hass.async_add_executor_job(is_within, out_path, bp_base):
        return {"error": "Refusing to write outside /config/blueprints/"}
    await hass.async_add_executor_job(os.makedirs, out_dir, 0o755, True)

    try:
        # Written verbatim: re-dumping would drop every !input tag. Provenance
        # goes in a header comment instead of a source_url mutation.
        # One line, whatever the caller passed: a newline in the URL would
        # otherwise inject YAML of its own choosing above the document.
        safe_url = " ".join(url.split())
        _import_content = f"# Imported by HACA from: {safe_url}\n\n{content}"
        await _async_write_file(hass, out_path, _import_content)
    except Exception as exc:
        return {"error": f"Failed to write blueprint: {exc}"}

    try:
        await hass.services.async_call("blueprint", "reload", blocking=True, context=_caller_context())
    except Exception:
        pass

    return {
        "success": True,
        "path": out_path,
        "name": bp_name,
        "domain": domain,
        "inputs": list(bp_inputs.keys()) if isinstance(bp_inputs, dict) else [],
        "message": (
            f"Blueprint '{bp_name}' imported to {out_path}. "
            "Visible in Settings → Blueprints."
        ),
    }
